import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './providers';
import Image from 'next/image';
import Navbar from './components/ui/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <Image
          src="/images/background.webp"
          alt="background"
          fill
          className="z-1 opacity-20"
        />
        <Providers>
          <Navbar />
          <main className="py-24 flex flex-col items-center min-h-screen px-4 z-[1000] relative">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
